from __future__ import annotations
import importlib
from typing import TYPE_CHECKING

__all__ = [
    'PronounceableText',
    'CssSelectorType',
    'Thing',
    'Person',
    'Place',
    'Event',
    'Intangible',
    'CreativeWork',
    'Action',
    'Product',
    'MedicalEntity',
    'StupidType',
    'Taxon',
    'Organization',
    'BioChemEntity',
    'Residence',
    'TouristDestination',
    'AdministrativeArea',
    'Landform',
    'LocalBusiness',
    'CivicStructure',
    'TouristAttraction',
    'Accommodation',
    'LandmarksOrHistoricalBuildings',
    'TheaterEvent',
    'FoodEvent',
    'EducationEvent',
    'Festival',
    'SocialEvent',
    'MusicEvent',
    'ScreeningEvent',
    'VisualArtsEvent',
    'LiteraryEvent',
    'UserInteraction',
    'DeliveryEvent',
    'SportsEvent',
    'PublicationEvent',
    'ComedyEvent',
    'CourseInstance',
    'ChildrensEvent',
    'DanceEvent',
    'BusinessEvent',
    'Hackathon',
    'SaleEvent',
    'ExhibitionEvent',
    'MediaSubscription',
    'VirtualLocation',
    'Ticket',
    'DataFeedItem',
    'Series',
    'Role',
    'FloorPlan',
    'Permit',
    'MemberProgramTier',
    'EducationalOccupationalProgram',
    'GeospatialGeometry',
    'Audience',
    'Brand',
    'Occupation',
    'ProgramMembership',
    'Service',
    'HealthPlanCostSharingSpecification',
    'Invoice',
    'HealthInsurancePlan',
    'Property',
    'AlignmentObject',
    'MerchantReturnPolicySeasonalOverride',
    'EnergyConsumptionDetails',
    'Schedule',
    'Enumeration',
    'SpeakableSpecification',
    'HealthPlanFormulary',
    'Language',
    'StructuredValue',
    'MemberProgram',
    'PropertyValueSpecification',
    'Rating',
    'DigitalDocumentPermission',
    'ComputerLanguage',
    'ProductReturnPolicy',
    'PaymentMethod',
    'ParcelDelivery',
    'MerchantReturnPolicy',
    'Reservation',
    'JobPosting',
    'BroadcastFrequencySpecification',
    'OccupationalExperienceRequirements',
    'BedDetails',
    'GameServer',
    'ServiceChannel',
    'Demand',
    'DefinedTerm',
    'ActionAccessSpecification',
    'FinancialIncentive',
    'MenuItem',
    'ListItem',
    'OrderItem',
    'ItemList',
    'HealthPlanNetwork',
    'Grant',
    'StatisticalPopulation',
    'Order',
    'ConstraintNode',
    'Offer',
    'Trip',
    'Observation',
    'EntryPoint',
    'Quantity',
    'Seat',
    'BroadcastChannel',
    '_Class',
    'Chapter',
    'TVSeries',
    'WebSite',
    'ComicStory',
    'HowTo',
    'WebContent',
    'Game',
    'Guide',
    'MediaObject',
    'DataCatalog',
    'Clip',
    'Review',
    'Certification',
    'Play',
    'SpecialAnnouncement',
    'ShortStory',
    'Photograph',
    'Claim',
    'Blog',
    'Quotation',
    'DigitalDocument',
    'Dataset',
    'CreativeWorkSeason',
    'LearningResource',
    'MusicPlaylist',
    'Menu',
    'Sculpture',
    'Painting',
    'WebPageElement',
    'Code',
    'Movie',
    'Poster',
    'HowToTip',
    'HowToSection',
    'MediaReviewItem',
    'Book',
    'Statement',
    'Season',
    'Article',
    'Atlas',
    'HowToDirection',
    'PublicationIssue',
    'Thesis',
    'SoftwareApplication',
    'PublicationVolume',
    'Comment',
    'MusicComposition',
    'ExercisePlan',
    'Message',
    'Conversation',
    'Drawing',
    'Map',
    'MusicRecording',
    'Legislation',
    'DefinedTermSet',
    'SoftwareSourceCode',
    'HyperTocEntry',
    'VisualArtwork',
    'SheetMusic',
    'Collection',
    'EducationalOccupationalCredential',
    'WebPage',
    'MenuSection',
    'Episode',
    'Manuscript',
    'CreativeWorkSeries',
    'MathSolver',
    'HyperToc',
    'ArchiveComponent',
    'ControlAction',
    'TradeAction',
    'AssessAction',
    'MoveAction',
    'AchieveAction',
    'FindAction',
    'TransferAction',
    'OrganizeAction',
    'UpdateAction',
    'CreateAction',
    'PlayAction',
    'SeekToAction',
    'SolveMathAction',
    'ConsumeAction',
    'InteractAction',
    'SearchAction',
    'ProductModel',
    'SomeProducts',
    'ProductGroup',
    'ProductCollection',
    'Vehicle',
    'IndividualProduct',
    'MedicalProcedure',
    'MedicalRiskFactor',
    'MedicalIndication',
    'MedicalTest',
    'MedicalRiskEstimator',
    'LifestyleModification',
    'Substance',
    'MedicalContraindication',
    'MedicalStudy',
    'MedicalCondition',
    'MedicalGuideline',
    'MedicalCause',
    'DrugClass',
    'MedicalDevice',
    'SuperficialAnatomy',
    'DrugCost',
    'AnatomicalStructure',
    'AnatomicalSystem',
    'MedicalIntangible',
    'NewsMediaOrganization',
    'NGO',
    'Cooperative',
    'SportsOrganization',
    'PerformingGroup',
    'FundingScheme',
    'SearchRescueOrganization',
    'LibrarySystem',
    'MedicalOrganization',
    'OnlineBusiness',
    'Consortium',
    'WorkersUnion',
    'GovernmentOrganization',
    'Project',
    'ResearchOrganization',
    'Airline',
    'Corporation',
    'PoliticalParty',
    'Protein',
    'Gene',
    'MolecularEntity',
    'ChemicalSubstance',
    'GatedResidenceCommunity',
    'ApartmentComplex',
    'Country',
    'City',
    'State',
    'SchoolDistrict',
    'Continent',
    'BodyOfWater',
    'Mountain',
    'Volcano',
    'RadioStation',
    'InternetCafe',
    'MedicalBusiness',
    'EmploymentAgency',
    'FoodEstablishment',
    'EntertainmentBusiness',
    'SportsActivityLocation',
    'ShoppingCenter',
    'FinancialService',
    'ChildCare',
    'HomeAndConstructionBusiness',
    'AutomotiveBusiness',
    'LodgingBusiness',
    'Store',
    'LegalService',
    'AnimalShelter',
    'TelevisionStation',
    'EmergencyService',
    'DryCleaningOrLaundry',
    'ArchiveOrganization',
    'RealEstateAgent',
    'Library',
    'RecyclingCenter',
    'GovernmentOffice',
    'TravelAgency',
    'TouristInformationCenter',
    'HealthAndBeautyBusiness',
    'ProfessionalService',
    'SelfStorage',
    'Playground',
    'MusicVenue',
    'Crematorium',
    'PoliceStation',
    'PlaceOfWorship',
    'PublicToilet',
    'TaxiStand',
    'TrainStation',
    'SubwayStation',
    'Bridge',
    'EventVenue',
    'BusStop',
    'EducationalOrganization',
    'BusStation',
    'Cemetery',
    'GovernmentBuilding',
    'Airport',
    'StadiumOrArena',
    'Beach',
    'Park',
    'RVPark',
    'PerformingArtsTheater',
    'BoatTerminal',
    'Hospital',
    'Aquarium',
    'Zoo',
    'ParkingFacility',
    'Museum',
    'MovieTheater',
    'FireStation',
    'Apartment',
    'Room',
    'Suite',
    'House',
    'CampingPitch',
    'UserCheckins',
    'UserBlocks',
    'UserComments',
    'UserTweets',
    'UserLikes',
    'UserPlays',
    'UserPageVisits',
    'UserPlusOnes',
    'UserDownloads',
    'OnDemandEvent',
    'BroadcastEvent',
    'EventSeries',
    'LinkRole',
    'PerformanceRole',
    'OrganizationRole',
    'GovernmentPermit',
    'WorkBasedProgram',
    'Researcher',
    'BusinessAudience',
    'EducationalAudience',
    'PeopleAudience',
    'MedicalAudience',
    'CableOrSatelliteService',
    'WebAPI',
    'FinancialProduct',
    'Taxi',
    'FoodService',
    'BroadcastService',
    'GovernmentService',
    'TaxiService',
    'SizeGroupEnumeration',
    'ReturnLabelSourceEnumeration',
    'PhysicalActivityCategory',
    'ContactPointOption',
    'PriceComponentTypeEnumeration',
    'MapCategoryType',
    'RestrictedDiet',
    'DigitalPlatformEnumeration',
    'PaymentMethodType',
    'IncentiveQualifiedExpenseType',
    'CertificationStatusEnumeration',
    'GovernmentBenefitsType',
    'StatusEnumeration',
    'CarUsageType',
    'FulfillmentTypeEnumeration',
    'SizeSystemEnumeration',
    'Specialty',
    'GenderType',
    'HealthAspectEnumeration',
    'MediaManipulationRatingEnumeration',
    'MediaEnumeration',
    'WarrantyScope',
    'MusicAlbumReleaseType',
    'MedicalEnumeration',
    'DigitalDocumentPermissionType',
    'OfferItemCondition',
    'MeasurementMethodEnum',
    'LegalValueLevel',
    'EnergyEfficiencyEnumeration',
    'BookFormatType',
    'BusinessEntityType',
    'ProductReturnEnumeration',
    'PriceTypeEnumeration',
    'ItemAvailability',
    'ItemListOrderType',
    'RefundTypeEnumeration',
    'TierBenefitEnumeration',
    'GameAvailabilityEnumeration',
    'BoardingPolicyType',
    'BusinessFunction',
    'DeliveryMethod',
    'IncentiveStatus',
    'PurchaseType',
    'QualitativeValue',
    'ReturnFeesEnumeration',
    'IncentiveType',
    'AdultOrientedEnumeration',
    'NonprofitType',
    'RsvpResponseType',
    'ReturnMethodEnumeration',
    'MerchantReturnEnumeration',
    'DayOfWeek',
    'MeasurementTypeEnumeration',
    'MusicReleaseFormatType',
    'EventAttendanceModeEnumeration',
    'MusicAlbumProductionType',
    'GamePlayMode',
    'DefinedRegion',
    'EngineSpecification',
    'ShippingService',
    'QuantitativeValue',
    'RepaymentSpecification',
    'ServicePeriod',
    'WarrantyPromise',
    'DeliveryTimeSettings',
    'ShippingRateSettings',
    'PriceSpecification',
    'QuantitativeValueDistribution',
    'ShippingDeliveryTime',
    'PostalCodeRangeSpecification',
    'MonetaryAmount',
    'ShippingConditions',
    'PropertyValue',
    'OwnershipInfo',
    'InteractionCounter',
    'ExchangeRateSpecification',
    'GeoShape',
    'CDCPMDRecord',
    'TypeAndQuantityNode',
    'OfferShippingDetails',
    'DatedMoneySpecification',
    'ContactPoint',
    'NutritionInformation',
    'GeoCoordinates',
    'OpeningHoursSpecification',
    'EndorsementRating',
    'AggregateRating',
    'RentalCarReservation',
    'LodgingReservation',
    'TrainReservation',
    'BoatReservation',
    'EventReservation',
    'FlightReservation',
    'BusReservation',
    'TaxiReservation',
    'ReservationPackage',
    'FoodEstablishmentReservation',
    'CategoryCode',
    'HowToItem',
    'BreadcrumbList',
    'HowToStep',
    'OfferCatalog',
    'MonetaryGrant',
    'StatisticalVariable',
    'AggregateOffer',
    'OfferForPurchase',
    'OfferForLease',
    'TrainTrip',
    'BusTrip',
    'TouristTrip',
    'Flight',
    'BoatTrip',
    'Energy',
    'Distance',
    'Mass',
    'Duration',
    'RadioChannel',
    'TelevisionChannel',
    'ComicCoverArt',
    'Recipe',
    'HealthTopicContent',
    'VideoGame',
    'VideoObject',
    'AudioObject',
    'MusicVideoObject',
    'AmpStory',
    'DataDownload',
    'TextObject',
    'ImageObject',
    '_3DModel',
    'RadioClip',
    'TVClip',
    'MovieClip',
    'VideoGameClip',
    'ClaimReview',
    'MediaReview',
    'UserReview',
    'EmployerReview',
    'Recommendation',
    'CriticReview',
    'NoteDigitalDocument',
    'SpreadsheetDigitalDocument',
    'TextDigitalDocument',
    'PresentationDigitalDocument',
    'DataFeed',
    'TVSeason',
    'RadioSeason',
    'PodcastSeason',
    'Quiz',
    'Course',
    'Syllabus',
    'MusicAlbum',
    'MusicRelease',
    'Table',
    'WPFooter',
    'WPSideBar',
    'WPAdBlock',
    'WPHeader',
    'SiteNavigationElement',
    'NewsArticle',
    'SatiricalArticle',
    'AdvertiserContentArticle',
    'SocialMediaPosting',
    'Report',
    'ScholarlyArticle',
    'TechArticle',
    'ComicIssue',
    'WebApplication',
    'MobileApplication',
    'CorrectionComment',
    'Question',
    'Answer',
    'EmailMessage',
    'LegislationObject',
    'CategoryCodeSet',
    'CoverArt',
    'RealEstateListing',
    'ProfilePage',
    'MedicalWebPage',
    'SearchResultsPage',
    'CheckoutPage',
    'ContactPage',
    'ItemPage',
    'CollectionPage',
    'AboutPage',
    'QAPage',
    'FAQPage',
    'RadioEpisode',
    'PodcastEpisode',
    'TVEpisode',
    'RadioSeries',
    'Periodical',
    'PodcastSeries',
    'BookSeries',
    'MovieSeries',
    'VideoGameSeries',
    'ResumeAction',
    'SuspendAction',
    'ActivateAction',
    'DeactivateAction',
    'RentAction',
    'OrderAction',
    'PreOrderAction',
    'BuyAction',
    'TipAction',
    'SellAction',
    'PayAction',
    'QuoteAction',
    'IgnoreAction',
    'ReviewAction',
    'ReactAction',
    'ChooseAction',
    'TravelAction',
    'DepartAction',
    'ArriveAction',
    'TieAction',
    'LoseAction',
    'WinAction',
    'TrackAction',
    'DiscoverAction',
    'CheckAction',
    'LendAction',
    'SendAction',
    'MoneyTransfer',
    'ReturnAction',
    'TakeAction',
    'GiveAction',
    'BorrowAction',
    'DonateAction',
    'ReceiveAction',
    'DownloadAction',
    'BookmarkAction',
    'PlanAction',
    'AllocateAction',
    'ApplyAction',
    'DeleteAction',
    'AddAction',
    'ReplaceAction',
    'DrawAction',
    'PhotographAction',
    'CookAction',
    'PaintAction',
    'FilmAction',
    'WriteAction',
    'PerformAction',
    'ExerciseAction',
    'InstallAction',
    'ReadAction',
    'ViewAction',
    'DrinkAction',
    'UseAction',
    'EatAction',
    'ListenAction',
    'PlayGameAction',
    'WatchAction',
    'MarryAction',
    'FollowAction',
    'JoinAction',
    'LeaveAction',
    'SubscribeAction',
    'RegisterAction',
    'CommunicateAction',
    'UnRegisterAction',
    'BefriendAction',
    'Car',
    'Motorcycle',
    'BusOrCoach',
    'MotorizedBicycle',
    'DiagnosticProcedure',
    'SurgicalProcedure',
    'TherapeuticProcedure',
    'TreatmentIndication',
    'ApprovedIndication',
    'PreventionIndication',
    'PathologyTest',
    'BloodTest',
    'ImagingTest',
    'MedicalTestPanel',
    'MedicalRiskCalculator',
    'MedicalRiskScore',
    'PhysicalActivity',
    'Diet',
    'Drug',
    'DietarySupplement',
    'MedicalTrial',
    'MedicalObservationalStudy',
    'InfectiousDisease',
    'MedicalSignOrSymptom',
    'MedicalGuidelineRecommendation',
    'MedicalGuidelineContraindication',
    'Vessel',
    'Ligament',
    'Bone',
    'BrainStructure',
    'Joint',
    'Muscle',
    'Nerve',
    'DoseSchedule',
    'MedicalConditionStage',
    'DrugStrength',
    'DDxElement',
    'MedicalCode',
    'DrugLegalStatus',
    'SportsTeam',
    'DanceGroup',
    'MusicGroup',
    'TheaterGroup',
    'VeterinaryCare',
    'DiagnosticLab',
    'MedicalClinic',
    'Pharmacy',
    'OnlineStore',
    'FundingAgency',
    'ResearchProject',
    'LakeBodyOfWater',
    'Reservoir',
    'Pond',
    'RiverBodyOfWater',
    'SeaBodyOfWater',
    'OceanBodyOfWater',
    'Waterfall',
    'Canal',
    'Dentist',
    'Physician',
    'Optician',
    'Winery',
    'IceCreamShop',
    'BarOrPub',
    'Restaurant',
    'Bakery',
    'CafeOrCoffeeShop',
    'FastFoodRestaurant',
    'Distillery',
    'Brewery',
    'ComedyClub',
    'AmusementPark',
    'Casino',
    'ArtGallery',
    'AdultEntertainment',
    'NightClub',
    'PublicSwimmingPool',
    'BowlingAlley',
    'TennisComplex',
    'GolfCourse',
    'ExerciseGym',
    'SportsClub',
    'InsuranceAgency',
    'BankOrCreditUnion',
    'AutomatedTeller',
    'AccountingService',
    'MovingCompany',
    'Locksmith',
    'GeneralContractor',
    'Plumber',
    'RoofingContractor',
    'HVACBusiness',
    'Electrician',
    'HousePainter',
    'AutoDealer',
    'AutoBodyShop',
    'GasStation',
    'MotorcycleDealer',
    'AutoRental',
    'AutoRepair',
    'AutoWash',
    'MotorcycleRepair',
    'BedAndBreakfast',
    'VacationRental',
    'Campground',
    'Resort',
    'Hotel',
    'Motel',
    'Hostel',
    'HobbyShop',
    'LiquorStore',
    'PawnShop',
    'ElectronicsStore',
    'BookStore',
    'Florist',
    'JewelryStore',
    'HardwareStore',
    'ComputerStore',
    'PetStore',
    'GardenStore',
    'OutletStore',
    'HomeGoodsStore',
    'DepartmentStore',
    'OfficeEquipmentStore',
    'ShoeStore',
    'MobilePhoneStore',
    'MusicStore',
    'BikeStore',
    'AutoPartsStore',
    'FurnitureStore',
    'GroceryStore',
    'MensClothingStore',
    'ConvenienceStore',
    'TireShop',
    'MovieRentalStore',
    'SportingGoodsStore',
    'WholesaleStore',
    'ClothingStore',
    'ToyStore',
    'Attorney',
    'Notary',
    'PostOffice',
    'DaySpa',
    'BeautySalon',
    'HealthClub',
    'HairSalon',
    'NailSalon',
    'TattooParlor',
    'HinduTemple',
    'BuddhistTemple',
    'Mosque',
    'Church',
    'Synagogue',
    'CollegeOrUniversity',
    'ElementarySchool',
    'School',
    'MiddleSchool',
    'HighSchool',
    'Preschool',
    'Embassy',
    'Courthouse',
    'DefenceEstablishment',
    'LegislativeBuilding',
    'CityHall',
    'MeetingRoom',
    'HotelRoom',
    'SingleFamilyResidence',
    'EmployeeRole',
    'ParentAudience',
    'Patient',
    'InvestmentOrDeposit',
    'PaymentService',
    'LoanOrCredit',
    'BankAccount',
    'CurrencyConversionService',
    'PaymentCard',
    'RadioBroadcastService',
    'WearableSizeGroupEnumeration',
    'PaymentStatusType',
    'ReservationStatusType',
    'GameServerStatus',
    'EventStatusType',
    'ActionStatusType',
    'OrderStatus',
    'LegalForceStatus',
    'WearableSizeSystemEnumeration',
    'MedicalSpecialty',
    'IPTCDigitalSourceEnumeration',
    'DrugPrescriptionStatus',
    'MedicalDevicePurpose',
    'MedicalTrialDesign',
    'DrugCostCategory',
    'MedicalProcedureType',
    'DrugPregnancyCategory',
    'PhysicalExam',
    'MedicalObservationalStudyDesign',
    'MedicalEvidenceLevel',
    'MedicalStudyStatus',
    'MedicalImagingTechnique',
    'MedicineSystem',
    'InfectiousAgentClass',
    'MedicalAudienceType',
    'EUEnergyEfficiencyEnumeration',
    'EnergyStarEnergyEfficiencyEnumeration',
    'BedType',
    'SteeringPositionValue',
    'SizeSpecification',
    'DriveWheelConfigurationValue',
    'USNonprofitType',
    'NLNonprofitType',
    'UKNonprofitType',
    'WearableMeasurementTypeEnumeration',
    'BodyMeasurementTypeEnumeration',
    'CompoundPriceSpecification',
    'UnitPriceSpecification',
    'PaymentChargeSpecification',
    'DeliveryChargeSpecification',
    'MonetaryAmountDistribution',
    'LocationFeatureSpecification',
    'GeoCircle',
    'PostalAddress',
    'EmployerAggregateRating',
    'HowToSupply',
    'HowToTool',
    'AMRadioChannel',
    'FMRadioChannel',
    'VideoObjectSnapshot',
    'AudioObjectSnapshot',
    'Audiobook',
    'ImageObjectSnapshot',
    'Barcode',
    'CompleteDataFeed',
    'OpinionNewsArticle',
    'ReviewNewsArticle',
    'ReportageNewsArticle',
    'BackgroundNewsArticle',
    'AnalysisNewsArticle',
    'AskPublicNewsArticle',
    'DiscussionForumPosting',
    'BlogPosting',
    'MedicalScholarlyArticle',
    'APIReference',
    'MediaGallery',
    'Newspaper',
    'ComicSeries',
    'DisagreeAction',
    'DislikeAction',
    'WantAction',
    'EndorseAction',
    'LikeAction',
    'AgreeAction',
    'VoteAction',
    'ScheduleAction',
    'CancelAction',
    'ReserveAction',
    'RejectAction',
    'AuthorizeAction',
    'AcceptAction',
    'AssignAction',
    'InsertAction',
    'WearAction',
    'CommentAction',
    'ReplyAction',
    'CheckOutAction',
    'InviteAction',
    'CheckInAction',
    'AskAction',
    'InformAction',
    'ShareAction',
    'PsychologicalTreatment',
    'MedicalTherapy',
    'MedicalSymptom',
    'MedicalSign',
    'Vein',
    'LymphaticVessel',
    'Artery',
    'MaximumDoseSchedule',
    'ReportedDoseSchedule',
    'RecommendedDoseSchedule',
    'CovidTestingFacility',
    'OnlineMarketplace',
    'PhysiciansOffice',
    'IndividualPhysician',
    'SkiResort',
    'CatholicChurch',
    'BrokerageAccount',
    'DepositAccount',
    'InvestmentFund',
    'MortgageLoan',
    'CreditCard',
    'LiveBlogPosting',
    'VideoGallery',
    'ImageGallery',
    'AppendAction',
    'PrependAction',
    'ConfirmAction',
    'RsvpAction',
    'OccupationalTherapy',
    'PalliativeProcedure',
    'PhysicalTherapy',
    'RadiationTherapy',
    'VitalSign'
]

_lazy_map = {
    'PronounceableText': '.pronounceable_text',
    'CssSelectorType': '.css_selector_type',
    'Thing': '.thing',
    'Person': '.person',
    'Place': '.place',
    'Event': '.event',
    'Intangible': '.intangible',
    'CreativeWork': '.creative_work',
    'Action': '.action',
    'Product': '.product',
    'MedicalEntity': '.medical_entity',
    'StupidType': '.stupid_type',
    'Taxon': '.taxon',
    'Organization': '.organization',
    'BioChemEntity': '.bio_chem_entity',
    'Residence': '.residence',
    'TouristDestination': '.tourist_destination',
    'AdministrativeArea': '.administrative_area',
    'Landform': '.landform',
    'LocalBusiness': '.local_business',
    'CivicStructure': '.civic_structure',
    'TouristAttraction': '.tourist_attraction',
    'Accommodation': '.accommodation',
    'LandmarksOrHistoricalBuildings': '.landmarks_or_historical_buildings',
    'TheaterEvent': '.theater_event',
    'FoodEvent': '.food_event',
    'EducationEvent': '.education_event',
    'Festival': '.festival',
    'SocialEvent': '.social_event',
    'MusicEvent': '.music_event',
    'ScreeningEvent': '.screening_event',
    'VisualArtsEvent': '.visual_arts_event',
    'LiteraryEvent': '.literary_event',
    'UserInteraction': '.user_interaction',
    'DeliveryEvent': '.delivery_event',
    'SportsEvent': '.sports_event',
    'PublicationEvent': '.publication_event',
    'ComedyEvent': '.comedy_event',
    'CourseInstance': '.course_instance',
    'ChildrensEvent': '.childrens_event',
    'DanceEvent': '.dance_event',
    'BusinessEvent': '.business_event',
    'Hackathon': '.hackathon',
    'SaleEvent': '.sale_event',
    'ExhibitionEvent': '.exhibition_event',
    'MediaSubscription': '.media_subscription',
    'VirtualLocation': '.virtual_location',
    'Ticket': '.ticket',
    'DataFeedItem': '.data_feed_item',
    'Series': '.series',
    'Role': '.role',
    'FloorPlan': '.floor_plan',
    'Permit': '.permit',
    'MemberProgramTier': '.member_program_tier',
    'EducationalOccupationalProgram': '.educational_occupational_program',
    'GeospatialGeometry': '.geospatial_geometry',
    'Audience': '.audience',
    'Brand': '.brand',
    'Occupation': '.occupation',
    'ProgramMembership': '.program_membership',
    'Service': '.service',
    'HealthPlanCostSharingSpecification': '.health_plan_cost_sharing_specification',
    'Invoice': '.invoice',
    'HealthInsurancePlan': '.health_insurance_plan',
    'Property': '.property',
    'AlignmentObject': '.alignment_object',
    'MerchantReturnPolicySeasonalOverride': '.merchant_return_policy_seasonal_override',
    'EnergyConsumptionDetails': '.energy_consumption_details',
    'Schedule': '.schedule',
    'Enumeration': '.enumeration',
    'SpeakableSpecification': '.speakable_specification',
    'HealthPlanFormulary': '.health_plan_formulary',
    'Language': '.language',
    'StructuredValue': '.structured_value',
    'MemberProgram': '.member_program',
    'PropertyValueSpecification': '.property_value_specification',
    'Rating': '.rating',
    'DigitalDocumentPermission': '.digital_document_permission',
    'ComputerLanguage': '.computer_language',
    'ProductReturnPolicy': '.product_return_policy',
    'PaymentMethod': '.payment_method',
    'ParcelDelivery': '.parcel_delivery',
    'MerchantReturnPolicy': '.merchant_return_policy',
    'Reservation': '.reservation',
    'JobPosting': '.job_posting',
    'BroadcastFrequencySpecification': '.broadcast_frequency_specification',
    'OccupationalExperienceRequirements': '.occupational_experience_requirements',
    'BedDetails': '.bed_details',
    'GameServer': '.game_server',
    'ServiceChannel': '.service_channel',
    'Demand': '.demand',
    'DefinedTerm': '.defined_term',
    'ActionAccessSpecification': '.action_access_specification',
    'FinancialIncentive': '.financial_incentive',
    'MenuItem': '.menu_item',
    'ListItem': '.list_item',
    'OrderItem': '.order_item',
    'ItemList': '.item_list',
    'HealthPlanNetwork': '.health_plan_network',
    'Grant': '.grant',
    'StatisticalPopulation': '.statistical_population',
    'Order': '.order',
    'ConstraintNode': '.constraint_node',
    'Offer': '.offer',
    'Trip': '.trip',
    'Observation': '.observation',
    'EntryPoint': '.entry_point',
    'Quantity': '.quantity',
    'Seat': '.seat',
    'BroadcastChannel': '.broadcast_channel',
    '_Class': '.__class',
    'Chapter': '.chapter',
    'TVSeries': '.tv_series',
    'WebSite': '.web_site',
    'ComicStory': '.comic_story',
    'HowTo': '.how_to',
    'WebContent': '.web_content',
    'Game': '.game',
    'Guide': '.guide',
    'MediaObject': '.media_object',
    'DataCatalog': '.data_catalog',
    'Clip': '.clip',
    'Review': '.review',
    'Certification': '.certification',
    'Play': '.play',
    'SpecialAnnouncement': '.special_announcement',
    'ShortStory': '.short_story',
    'Photograph': '.photograph',
    'Claim': '.claim',
    'Blog': '.blog',
    'Quotation': '.quotation',
    'DigitalDocument': '.digital_document',
    'Dataset': '.dataset',
    'CreativeWorkSeason': '.creative_work_season',
    'LearningResource': '.learning_resource',
    'MusicPlaylist': '.music_playlist',
    'Menu': '.menu',
    'Sculpture': '.sculpture',
    'Painting': '.painting',
    'WebPageElement': '.web_page_element',
    'Code': '.code',
    'Movie': '.movie',
    'Poster': '.poster',
    'HowToTip': '.how_to_tip',
    'HowToSection': '.how_to_section',
    'MediaReviewItem': '.media_review_item',
    'Book': '.book',
    'Statement': '.statement',
    'Season': '.season',
    'Article': '.article',
    'Atlas': '.atlas',
    'HowToDirection': '.how_to_direction',
    'PublicationIssue': '.publication_issue',
    'Thesis': '.thesis',
    'SoftwareApplication': '.software_application',
    'PublicationVolume': '.publication_volume',
    'Comment': '.comment',
    'MusicComposition': '.music_composition',
    'ExercisePlan': '.exercise_plan',
    'Message': '.message',
    'Conversation': '.conversation',
    'Drawing': '.drawing',
    'Map': '.map',
    'MusicRecording': '.music_recording',
    'Legislation': '.legislation',
    'DefinedTermSet': '.defined_term_set',
    'SoftwareSourceCode': '.software_source_code',
    'HyperTocEntry': '.hyper_toc_entry',
    'VisualArtwork': '.visual_artwork',
    'SheetMusic': '.sheet_music',
    'Collection': '.collection',
    'EducationalOccupationalCredential': '.educational_occupational_credential',
    'WebPage': '.web_page',
    'MenuSection': '.menu_section',
    'Episode': '.episode',
    'Manuscript': '.manuscript',
    'CreativeWorkSeries': '.creative_work_series',
    'MathSolver': '.math_solver',
    'HyperToc': '.hyper_toc',
    'ArchiveComponent': '.archive_component',
    'ControlAction': '.control_action',
    'TradeAction': '.trade_action',
    'AssessAction': '.assess_action',
    'MoveAction': '.move_action',
    'AchieveAction': '.achieve_action',
    'FindAction': '.find_action',
    'TransferAction': '.transfer_action',
    'OrganizeAction': '.organize_action',
    'UpdateAction': '.update_action',
    'CreateAction': '.create_action',
    'PlayAction': '.play_action',
    'SeekToAction': '.seek_to_action',
    'SolveMathAction': '.solve_math_action',
    'ConsumeAction': '.consume_action',
    'InteractAction': '.interact_action',
    'SearchAction': '.search_action',
    'ProductModel': '.product_model',
    'SomeProducts': '.some_products',
    'ProductGroup': '.product_group',
    'ProductCollection': '.product_collection',
    'Vehicle': '.vehicle',
    'IndividualProduct': '.individual_product',
    'MedicalProcedure': '.medical_procedure',
    'MedicalRiskFactor': '.medical_risk_factor',
    'MedicalIndication': '.medical_indication',
    'MedicalTest': '.medical_test',
    'MedicalRiskEstimator': '.medical_risk_estimator',
    'LifestyleModification': '.lifestyle_modification',
    'Substance': '.substance',
    'MedicalContraindication': '.medical_contraindication',
    'MedicalStudy': '.medical_study',
    'MedicalCondition': '.medical_condition',
    'MedicalGuideline': '.medical_guideline',
    'MedicalCause': '.medical_cause',
    'DrugClass': '.drug_class',
    'MedicalDevice': '.medical_device',
    'SuperficialAnatomy': '.superficial_anatomy',
    'DrugCost': '.drug_cost',
    'AnatomicalStructure': '.anatomical_structure',
    'AnatomicalSystem': '.anatomical_system',
    'MedicalIntangible': '.medical_intangible',
    'NewsMediaOrganization': '.news_media_organization',
    'NGO': '.ngo',
    'Cooperative': '.cooperative',
    'SportsOrganization': '.sports_organization',
    'PerformingGroup': '.performing_group',
    'FundingScheme': '.funding_scheme',
    'SearchRescueOrganization': '.search_rescue_organization',
    'LibrarySystem': '.library_system',
    'MedicalOrganization': '.medical_organization',
    'OnlineBusiness': '.online_business',
    'Consortium': '.consortium',
    'WorkersUnion': '.workers_union',
    'GovernmentOrganization': '.government_organization',
    'Project': '.project',
    'ResearchOrganization': '.research_organization',
    'Airline': '.airline',
    'Corporation': '.corporation',
    'PoliticalParty': '.political_party',
    'Protein': '.protein',
    'Gene': '.gene',
    'MolecularEntity': '.molecular_entity',
    'ChemicalSubstance': '.chemical_substance',
    'GatedResidenceCommunity': '.gated_residence_community',
    'ApartmentComplex': '.apartment_complex',
    'Country': '.country',
    'City': '.city',
    'State': '.state',
    'SchoolDistrict': '.school_district',
    'Continent': '.continent',
    'BodyOfWater': '.body_of_water',
    'Mountain': '.mountain',
    'Volcano': '.volcano',
    'RadioStation': '.radio_station',
    'InternetCafe': '.internet_cafe',
    'MedicalBusiness': '.medical_business',
    'EmploymentAgency': '.employment_agency',
    'FoodEstablishment': '.food_establishment',
    'EntertainmentBusiness': '.entertainment_business',
    'SportsActivityLocation': '.sports_activity_location',
    'ShoppingCenter': '.shopping_center',
    'FinancialService': '.financial_service',
    'ChildCare': '.child_care',
    'HomeAndConstructionBusiness': '.home_and_construction_business',
    'AutomotiveBusiness': '.automotive_business',
    'LodgingBusiness': '.lodging_business',
    'Store': '.store',
    'LegalService': '.legal_service',
    'AnimalShelter': '.animal_shelter',
    'TelevisionStation': '.television_station',
    'EmergencyService': '.emergency_service',
    'DryCleaningOrLaundry': '.dry_cleaning_or_laundry',
    'ArchiveOrganization': '.archive_organization',
    'RealEstateAgent': '.real_estate_agent',
    'Library': '.library',
    'RecyclingCenter': '.recycling_center',
    'GovernmentOffice': '.government_office',
    'TravelAgency': '.travel_agency',
    'TouristInformationCenter': '.tourist_information_center',
    'HealthAndBeautyBusiness': '.health_and_beauty_business',
    'ProfessionalService': '.professional_service',
    'SelfStorage': '.self_storage',
    'Playground': '.playground',
    'MusicVenue': '.music_venue',
    'Crematorium': '.crematorium',
    'PoliceStation': '.police_station',
    'PlaceOfWorship': '.place_of_worship',
    'PublicToilet': '.public_toilet',
    'TaxiStand': '.taxi_stand',
    'TrainStation': '.train_station',
    'SubwayStation': '.subway_station',
    'Bridge': '.bridge',
    'EventVenue': '.event_venue',
    'BusStop': '.bus_stop',
    'EducationalOrganization': '.educational_organization',
    'BusStation': '.bus_station',
    'Cemetery': '.cemetery',
    'GovernmentBuilding': '.government_building',
    'Airport': '.airport',
    'StadiumOrArena': '.stadium_or_arena',
    'Beach': '.beach',
    'Park': '.park',
    'RVPark': '.rv_park',
    'PerformingArtsTheater': '.performing_arts_theater',
    'BoatTerminal': '.boat_terminal',
    'Hospital': '.hospital',
    'Aquarium': '.aquarium',
    'Zoo': '.zoo',
    'ParkingFacility': '.parking_facility',
    'Museum': '.museum',
    'MovieTheater': '.movie_theater',
    'FireStation': '.fire_station',
    'Apartment': '.apartment',
    'Room': '.room',
    'Suite': '.suite',
    'House': '.house',
    'CampingPitch': '.camping_pitch',
    'UserCheckins': '.user_checkins',
    'UserBlocks': '.user_blocks',
    'UserComments': '.user_comments',
    'UserTweets': '.user_tweets',
    'UserLikes': '.user_likes',
    'UserPlays': '.user_plays',
    'UserPageVisits': '.user_page_visits',
    'UserPlusOnes': '.user_plus_ones',
    'UserDownloads': '.user_downloads',
    'OnDemandEvent': '.on_demand_event',
    'BroadcastEvent': '.broadcast_event',
    'EventSeries': '.event_series',
    'LinkRole': '.link_role',
    'PerformanceRole': '.performance_role',
    'OrganizationRole': '.organization_role',
    'GovernmentPermit': '.government_permit',
    'WorkBasedProgram': '.work_based_program',
    'Researcher': '.researcher',
    'BusinessAudience': '.business_audience',
    'EducationalAudience': '.educational_audience',
    'PeopleAudience': '.people_audience',
    'MedicalAudience': '.medical_audience',
    'CableOrSatelliteService': '.cable_or_satellite_service',
    'WebAPI': '.web_api',
    'FinancialProduct': '.financial_product',
    'Taxi': '.taxi',
    'FoodService': '.food_service',
    'BroadcastService': '.broadcast_service',
    'GovernmentService': '.government_service',
    'TaxiService': '.taxi_service',
    'SizeGroupEnumeration': '.size_group_enumeration',
    'ReturnLabelSourceEnumeration': '.return_label_source_enumeration',
    'PhysicalActivityCategory': '.physical_activity_category',
    'ContactPointOption': '.contact_point_option',
    'PriceComponentTypeEnumeration': '.price_component_type_enumeration',
    'MapCategoryType': '.map_category_type',
    'RestrictedDiet': '.restricted_diet',
    'DigitalPlatformEnumeration': '.digital_platform_enumeration',
    'PaymentMethodType': '.payment_method_type',
    'IncentiveQualifiedExpenseType': '.incentive_qualified_expense_type',
    'CertificationStatusEnumeration': '.certification_status_enumeration',
    'GovernmentBenefitsType': '.government_benefits_type',
    'StatusEnumeration': '.status_enumeration',
    'CarUsageType': '.car_usage_type',
    'FulfillmentTypeEnumeration': '.fulfillment_type_enumeration',
    'SizeSystemEnumeration': '.size_system_enumeration',
    'Specialty': '.specialty',
    'GenderType': '.gender_type',
    'HealthAspectEnumeration': '.health_aspect_enumeration',
    'MediaManipulationRatingEnumeration': '.media_manipulation_rating_enumeration',
    'MediaEnumeration': '.media_enumeration',
    'WarrantyScope': '.warranty_scope',
    'MusicAlbumReleaseType': '.music_album_release_type',
    'MedicalEnumeration': '.medical_enumeration',
    'DigitalDocumentPermissionType': '.digital_document_permission_type',
    'OfferItemCondition': '.offer_item_condition',
    'MeasurementMethodEnum': '.measurement_method_enum',
    'LegalValueLevel': '.legal_value_level',
    'EnergyEfficiencyEnumeration': '.energy_efficiency_enumeration',
    'BookFormatType': '.book_format_type',
    'BusinessEntityType': '.business_entity_type',
    'ProductReturnEnumeration': '.product_return_enumeration',
    'PriceTypeEnumeration': '.price_type_enumeration',
    'ItemAvailability': '.item_availability',
    'ItemListOrderType': '.item_list_order_type',
    'RefundTypeEnumeration': '.refund_type_enumeration',
    'TierBenefitEnumeration': '.tier_benefit_enumeration',
    'GameAvailabilityEnumeration': '.game_availability_enumeration',
    'BoardingPolicyType': '.boarding_policy_type',
    'BusinessFunction': '.business_function',
    'DeliveryMethod': '.delivery_method',
    'IncentiveStatus': '.incentive_status',
    'PurchaseType': '.purchase_type',
    'QualitativeValue': '.qualitative_value',
    'ReturnFeesEnumeration': '.return_fees_enumeration',
    'IncentiveType': '.incentive_type',
    'AdultOrientedEnumeration': '.adult_oriented_enumeration',
    'NonprofitType': '.nonprofit_type',
    'RsvpResponseType': '.rsvp_response_type',
    'ReturnMethodEnumeration': '.return_method_enumeration',
    'MerchantReturnEnumeration': '.merchant_return_enumeration',
    'DayOfWeek': '.day_of_week',
    'MeasurementTypeEnumeration': '.measurement_type_enumeration',
    'MusicReleaseFormatType': '.music_release_format_type',
    'EventAttendanceModeEnumeration': '.event_attendance_mode_enumeration',
    'MusicAlbumProductionType': '.music_album_production_type',
    'GamePlayMode': '.game_play_mode',
    'DefinedRegion': '.defined_region',
    'EngineSpecification': '.engine_specification',
    'ShippingService': '.shipping_service',
    'QuantitativeValue': '.quantitative_value',
    'RepaymentSpecification': '.repayment_specification',
    'ServicePeriod': '.service_period',
    'WarrantyPromise': '.warranty_promise',
    'DeliveryTimeSettings': '.delivery_time_settings',
    'ShippingRateSettings': '.shipping_rate_settings',
    'PriceSpecification': '.price_specification',
    'QuantitativeValueDistribution': '.quantitative_value_distribution',
    'ShippingDeliveryTime': '.shipping_delivery_time',
    'PostalCodeRangeSpecification': '.postal_code_range_specification',
    'MonetaryAmount': '.monetary_amount',
    'ShippingConditions': '.shipping_conditions',
    'PropertyValue': '.property_value',
    'OwnershipInfo': '.ownership_info',
    'InteractionCounter': '.interaction_counter',
    'ExchangeRateSpecification': '.exchange_rate_specification',
    'GeoShape': '.geo_shape',
    'CDCPMDRecord': '.cdcpmd_record',
    'TypeAndQuantityNode': '.type_and_quantity_node',
    'OfferShippingDetails': '.offer_shipping_details',
    'DatedMoneySpecification': '.dated_money_specification',
    'ContactPoint': '.contact_point',
    'NutritionInformation': '.nutrition_information',
    'GeoCoordinates': '.geo_coordinates',
    'OpeningHoursSpecification': '.opening_hours_specification',
    'EndorsementRating': '.endorsement_rating',
    'AggregateRating': '.aggregate_rating',
    'RentalCarReservation': '.rental_car_reservation',
    'LodgingReservation': '.lodging_reservation',
    'TrainReservation': '.train_reservation',
    'BoatReservation': '.boat_reservation',
    'EventReservation': '.event_reservation',
    'FlightReservation': '.flight_reservation',
    'BusReservation': '.bus_reservation',
    'TaxiReservation': '.taxi_reservation',
    'ReservationPackage': '.reservation_package',
    'FoodEstablishmentReservation': '.food_establishment_reservation',
    'CategoryCode': '.category_code',
    'HowToItem': '.how_to_item',
    'BreadcrumbList': '.breadcrumb_list',
    'HowToStep': '.how_to_step',
    'OfferCatalog': '.offer_catalog',
    'MonetaryGrant': '.monetary_grant',
    'StatisticalVariable': '.statistical_variable',
    'AggregateOffer': '.aggregate_offer',
    'OfferForPurchase': '.offer_for_purchase',
    'OfferForLease': '.offer_for_lease',
    'TrainTrip': '.train_trip',
    'BusTrip': '.bus_trip',
    'TouristTrip': '.tourist_trip',
    'Flight': '.flight',
    'BoatTrip': '.boat_trip',
    'Energy': '.energy',
    'Distance': '.distance',
    'Mass': '.mass',
    'Duration': '.duration',
    'RadioChannel': '.radio_channel',
    'TelevisionChannel': '.television_channel',
    'ComicCoverArt': '.comic_cover_art',
    'Recipe': '.recipe',
    'HealthTopicContent': '.health_topic_content',
    'VideoGame': '.video_game',
    'VideoObject': '.video_object',
    'AudioObject': '.audio_object',
    'MusicVideoObject': '.music_video_object',
    'AmpStory': '.amp_story',
    'DataDownload': '.data_download',
    'TextObject': '.text_object',
    'ImageObject': '.image_object',
    '_3DModel': '._3_d_model',
    'RadioClip': '.radio_clip',
    'TVClip': '.tv_clip',
    'MovieClip': '.movie_clip',
    'VideoGameClip': '.video_game_clip',
    'ClaimReview': '.claim_review',
    'MediaReview': '.media_review',
    'UserReview': '.user_review',
    'EmployerReview': '.employer_review',
    'Recommendation': '.recommendation',
    'CriticReview': '.critic_review',
    'NoteDigitalDocument': '.note_digital_document',
    'SpreadsheetDigitalDocument': '.spreadsheet_digital_document',
    'TextDigitalDocument': '.text_digital_document',
    'PresentationDigitalDocument': '.presentation_digital_document',
    'DataFeed': '.data_feed',
    'TVSeason': '.tv_season',
    'RadioSeason': '.radio_season',
    'PodcastSeason': '.podcast_season',
    'Quiz': '.quiz',
    'Course': '.course',
    'Syllabus': '.syllabus',
    'MusicAlbum': '.music_album',
    'MusicRelease': '.music_release',
    'Table': '.table',
    'WPFooter': '.wp_footer',
    'WPSideBar': '.wp_side_bar',
    'WPAdBlock': '.wp_ad_block',
    'WPHeader': '.wp_header',
    'SiteNavigationElement': '.site_navigation_element',
    'NewsArticle': '.news_article',
    'SatiricalArticle': '.satirical_article',
    'AdvertiserContentArticle': '.advertiser_content_article',
    'SocialMediaPosting': '.social_media_posting',
    'Report': '.report',
    'ScholarlyArticle': '.scholarly_article',
    'TechArticle': '.tech_article',
    'ComicIssue': '.comic_issue',
    'WebApplication': '.web_application',
    'MobileApplication': '.mobile_application',
    'CorrectionComment': '.correction_comment',
    'Question': '.question',
    'Answer': '.answer',
    'EmailMessage': '.email_message',
    'LegislationObject': '.legislation_object',
    'CategoryCodeSet': '.category_code_set',
    'CoverArt': '.cover_art',
    'RealEstateListing': '.real_estate_listing',
    'ProfilePage': '.profile_page',
    'MedicalWebPage': '.medical_web_page',
    'SearchResultsPage': '.search_results_page',
    'CheckoutPage': '.checkout_page',
    'ContactPage': '.contact_page',
    'ItemPage': '.item_page',
    'CollectionPage': '.collection_page',
    'AboutPage': '.about_page',
    'QAPage': '.qa_page',
    'FAQPage': '.faq_page',
    'RadioEpisode': '.radio_episode',
    'PodcastEpisode': '.podcast_episode',
    'TVEpisode': '.tv_episode',
    'RadioSeries': '.radio_series',
    'Periodical': '.periodical',
    'PodcastSeries': '.podcast_series',
    'BookSeries': '.book_series',
    'MovieSeries': '.movie_series',
    'VideoGameSeries': '.video_game_series',
    'ResumeAction': '.resume_action',
    'SuspendAction': '.suspend_action',
    'ActivateAction': '.activate_action',
    'DeactivateAction': '.deactivate_action',
    'RentAction': '.rent_action',
    'OrderAction': '.order_action',
    'PreOrderAction': '.pre_order_action',
    'BuyAction': '.buy_action',
    'TipAction': '.tip_action',
    'SellAction': '.sell_action',
    'PayAction': '.pay_action',
    'QuoteAction': '.quote_action',
    'IgnoreAction': '.ignore_action',
    'ReviewAction': '.review_action',
    'ReactAction': '.react_action',
    'ChooseAction': '.choose_action',
    'TravelAction': '.travel_action',
    'DepartAction': '.depart_action',
    'ArriveAction': '.arrive_action',
    'TieAction': '.tie_action',
    'LoseAction': '.lose_action',
    'WinAction': '.win_action',
    'TrackAction': '.track_action',
    'DiscoverAction': '.discover_action',
    'CheckAction': '.check_action',
    'LendAction': '.lend_action',
    'SendAction': '.send_action',
    'MoneyTransfer': '.money_transfer',
    'ReturnAction': '.return_action',
    'TakeAction': '.take_action',
    'GiveAction': '.give_action',
    'BorrowAction': '.borrow_action',
    'DonateAction': '.donate_action',
    'ReceiveAction': '.receive_action',
    'DownloadAction': '.download_action',
    'BookmarkAction': '.bookmark_action',
    'PlanAction': '.plan_action',
    'AllocateAction': '.allocate_action',
    'ApplyAction': '.apply_action',
    'DeleteAction': '.delete_action',
    'AddAction': '.add_action',
    'ReplaceAction': '.replace_action',
    'DrawAction': '.draw_action',
    'PhotographAction': '.photograph_action',
    'CookAction': '.cook_action',
    'PaintAction': '.paint_action',
    'FilmAction': '.film_action',
    'WriteAction': '.write_action',
    'PerformAction': '.perform_action',
    'ExerciseAction': '.exercise_action',
    'InstallAction': '.install_action',
    'ReadAction': '.read_action',
    'ViewAction': '.view_action',
    'DrinkAction': '.drink_action',
    'UseAction': '.use_action',
    'EatAction': '.eat_action',
    'ListenAction': '.listen_action',
    'PlayGameAction': '.play_game_action',
    'WatchAction': '.watch_action',
    'MarryAction': '.marry_action',
    'FollowAction': '.follow_action',
    'JoinAction': '.join_action',
    'LeaveAction': '.leave_action',
    'SubscribeAction': '.subscribe_action',
    'RegisterAction': '.register_action',
    'CommunicateAction': '.communicate_action',
    'UnRegisterAction': '.un_register_action',
    'BefriendAction': '.befriend_action',
    'Car': '.car',
    'Motorcycle': '.motorcycle',
    'BusOrCoach': '.bus_or_coach',
    'MotorizedBicycle': '.motorized_bicycle',
    'DiagnosticProcedure': '.diagnostic_procedure',
    'SurgicalProcedure': '.surgical_procedure',
    'TherapeuticProcedure': '.therapeutic_procedure',
    'TreatmentIndication': '.treatment_indication',
    'ApprovedIndication': '.approved_indication',
    'PreventionIndication': '.prevention_indication',
    'PathologyTest': '.pathology_test',
    'BloodTest': '.blood_test',
    'ImagingTest': '.imaging_test',
    'MedicalTestPanel': '.medical_test_panel',
    'MedicalRiskCalculator': '.medical_risk_calculator',
    'MedicalRiskScore': '.medical_risk_score',
    'PhysicalActivity': '.physical_activity',
    'Diet': '.diet',
    'Drug': '.drug',
    'DietarySupplement': '.dietary_supplement',
    'MedicalTrial': '.medical_trial',
    'MedicalObservationalStudy': '.medical_observational_study',
    'InfectiousDisease': '.infectious_disease',
    'MedicalSignOrSymptom': '.medical_sign_or_symptom',
    'MedicalGuidelineRecommendation': '.medical_guideline_recommendation',
    'MedicalGuidelineContraindication': '.medical_guideline_contraindication',
    'Vessel': '.vessel',
    'Ligament': '.ligament',
    'Bone': '.bone',
    'BrainStructure': '.brain_structure',
    'Joint': '.joint',
    'Muscle': '.muscle',
    'Nerve': '.nerve',
    'DoseSchedule': '.dose_schedule',
    'MedicalConditionStage': '.medical_condition_stage',
    'DrugStrength': '.drug_strength',
    'DDxElement': '.d_dx_element',
    'MedicalCode': '.medical_code',
    'DrugLegalStatus': '.drug_legal_status',
    'SportsTeam': '.sports_team',
    'DanceGroup': '.dance_group',
    'MusicGroup': '.music_group',
    'TheaterGroup': '.theater_group',
    'VeterinaryCare': '.veterinary_care',
    'DiagnosticLab': '.diagnostic_lab',
    'MedicalClinic': '.medical_clinic',
    'Pharmacy': '.pharmacy',
    'OnlineStore': '.online_store',
    'FundingAgency': '.funding_agency',
    'ResearchProject': '.research_project',
    'LakeBodyOfWater': '.lake_body_of_water',
    'Reservoir': '.reservoir',
    'Pond': '.pond',
    'RiverBodyOfWater': '.river_body_of_water',
    'SeaBodyOfWater': '.sea_body_of_water',
    'OceanBodyOfWater': '.ocean_body_of_water',
    'Waterfall': '.waterfall',
    'Canal': '.canal',
    'Dentist': '.dentist',
    'Physician': '.physician',
    'Optician': '.optician',
    'Winery': '.winery',
    'IceCreamShop': '.ice_cream_shop',
    'BarOrPub': '.bar_or_pub',
    'Restaurant': '.restaurant',
    'Bakery': '.bakery',
    'CafeOrCoffeeShop': '.cafe_or_coffee_shop',
    'FastFoodRestaurant': '.fast_food_restaurant',
    'Distillery': '.distillery',
    'Brewery': '.brewery',
    'ComedyClub': '.comedy_club',
    'AmusementPark': '.amusement_park',
    'Casino': '.casino',
    'ArtGallery': '.art_gallery',
    'AdultEntertainment': '.adult_entertainment',
    'NightClub': '.night_club',
    'PublicSwimmingPool': '.public_swimming_pool',
    'BowlingAlley': '.bowling_alley',
    'TennisComplex': '.tennis_complex',
    'GolfCourse': '.golf_course',
    'ExerciseGym': '.exercise_gym',
    'SportsClub': '.sports_club',
    'InsuranceAgency': '.insurance_agency',
    'BankOrCreditUnion': '.bank_or_credit_union',
    'AutomatedTeller': '.automated_teller',
    'AccountingService': '.accounting_service',
    'MovingCompany': '.moving_company',
    'Locksmith': '.locksmith',
    'GeneralContractor': '.general_contractor',
    'Plumber': '.plumber',
    'RoofingContractor': '.roofing_contractor',
    'HVACBusiness': '.hvac_business',
    'Electrician': '.electrician',
    'HousePainter': '.house_painter',
    'AutoDealer': '.auto_dealer',
    'AutoBodyShop': '.auto_body_shop',
    'GasStation': '.gas_station',
    'MotorcycleDealer': '.motorcycle_dealer',
    'AutoRental': '.auto_rental',
    'AutoRepair': '.auto_repair',
    'AutoWash': '.auto_wash',
    'MotorcycleRepair': '.motorcycle_repair',
    'BedAndBreakfast': '.bed_and_breakfast',
    'VacationRental': '.vacation_rental',
    'Campground': '.campground',
    'Resort': '.resort',
    'Hotel': '.hotel',
    'Motel': '.motel',
    'Hostel': '.hostel',
    'HobbyShop': '.hobby_shop',
    'LiquorStore': '.liquor_store',
    'PawnShop': '.pawn_shop',
    'ElectronicsStore': '.electronics_store',
    'BookStore': '.book_store',
    'Florist': '.florist',
    'JewelryStore': '.jewelry_store',
    'HardwareStore': '.hardware_store',
    'ComputerStore': '.computer_store',
    'PetStore': '.pet_store',
    'GardenStore': '.garden_store',
    'OutletStore': '.outlet_store',
    'HomeGoodsStore': '.home_goods_store',
    'DepartmentStore': '.department_store',
    'OfficeEquipmentStore': '.office_equipment_store',
    'ShoeStore': '.shoe_store',
    'MobilePhoneStore': '.mobile_phone_store',
    'MusicStore': '.music_store',
    'BikeStore': '.bike_store',
    'AutoPartsStore': '.auto_parts_store',
    'FurnitureStore': '.furniture_store',
    'GroceryStore': '.grocery_store',
    'MensClothingStore': '.mens_clothing_store',
    'ConvenienceStore': '.convenience_store',
    'TireShop': '.tire_shop',
    'MovieRentalStore': '.movie_rental_store',
    'SportingGoodsStore': '.sporting_goods_store',
    'WholesaleStore': '.wholesale_store',
    'ClothingStore': '.clothing_store',
    'ToyStore': '.toy_store',
    'Attorney': '.attorney',
    'Notary': '.notary',
    'PostOffice': '.post_office',
    'DaySpa': '.day_spa',
    'BeautySalon': '.beauty_salon',
    'HealthClub': '.health_club',
    'HairSalon': '.hair_salon',
    'NailSalon': '.nail_salon',
    'TattooParlor': '.tattoo_parlor',
    'HinduTemple': '.hindu_temple',
    'BuddhistTemple': '.buddhist_temple',
    'Mosque': '.mosque',
    'Church': '.church',
    'Synagogue': '.synagogue',
    'CollegeOrUniversity': '.college_or_university',
    'ElementarySchool': '.elementary_school',
    'School': '.school',
    'MiddleSchool': '.middle_school',
    'HighSchool': '.high_school',
    'Preschool': '.preschool',
    'Embassy': '.embassy',
    'Courthouse': '.courthouse',
    'DefenceEstablishment': '.defence_establishment',
    'LegislativeBuilding': '.legislative_building',
    'CityHall': '.city_hall',
    'MeetingRoom': '.meeting_room',
    'HotelRoom': '.hotel_room',
    'SingleFamilyResidence': '.single_family_residence',
    'EmployeeRole': '.employee_role',
    'ParentAudience': '.parent_audience',
    'Patient': '.patient',
    'InvestmentOrDeposit': '.investment_or_deposit',
    'PaymentService': '.payment_service',
    'LoanOrCredit': '.loan_or_credit',
    'BankAccount': '.bank_account',
    'CurrencyConversionService': '.currency_conversion_service',
    'PaymentCard': '.payment_card',
    'RadioBroadcastService': '.radio_broadcast_service',
    'WearableSizeGroupEnumeration': '.wearable_size_group_enumeration',
    'PaymentStatusType': '.payment_status_type',
    'ReservationStatusType': '.reservation_status_type',
    'GameServerStatus': '.game_server_status',
    'EventStatusType': '.event_status_type',
    'ActionStatusType': '.action_status_type',
    'OrderStatus': '.order_status',
    'LegalForceStatus': '.legal_force_status',
    'WearableSizeSystemEnumeration': '.wearable_size_system_enumeration',
    'MedicalSpecialty': '.medical_specialty',
    'IPTCDigitalSourceEnumeration': '.iptc_digital_source_enumeration',
    'DrugPrescriptionStatus': '.drug_prescription_status',
    'MedicalDevicePurpose': '.medical_device_purpose',
    'MedicalTrialDesign': '.medical_trial_design',
    'DrugCostCategory': '.drug_cost_category',
    'MedicalProcedureType': '.medical_procedure_type',
    'DrugPregnancyCategory': '.drug_pregnancy_category',
    'PhysicalExam': '.physical_exam',
    'MedicalObservationalStudyDesign': '.medical_observational_study_design',
    'MedicalEvidenceLevel': '.medical_evidence_level',
    'MedicalStudyStatus': '.medical_study_status',
    'MedicalImagingTechnique': '.medical_imaging_technique',
    'MedicineSystem': '.medicine_system',
    'InfectiousAgentClass': '.infectious_agent_class',
    'MedicalAudienceType': '.medical_audience_type',
    'EUEnergyEfficiencyEnumeration': '.eu_energy_efficiency_enumeration',
    'EnergyStarEnergyEfficiencyEnumeration': '.energy_star_energy_efficiency_enumeration',
    'BedType': '.bed_type',
    'SteeringPositionValue': '.steering_position_value',
    'SizeSpecification': '.size_specification',
    'DriveWheelConfigurationValue': '.drive_wheel_configuration_value',
    'USNonprofitType': '.us_nonprofit_type',
    'NLNonprofitType': '.nl_nonprofit_type',
    'UKNonprofitType': '.uk_nonprofit_type',
    'WearableMeasurementTypeEnumeration': '.wearable_measurement_type_enumeration',
    'BodyMeasurementTypeEnumeration': '.body_measurement_type_enumeration',
    'CompoundPriceSpecification': '.compound_price_specification',
    'UnitPriceSpecification': '.unit_price_specification',
    'PaymentChargeSpecification': '.payment_charge_specification',
    'DeliveryChargeSpecification': '.delivery_charge_specification',
    'MonetaryAmountDistribution': '.monetary_amount_distribution',
    'LocationFeatureSpecification': '.location_feature_specification',
    'GeoCircle': '.geo_circle',
    'PostalAddress': '.postal_address',
    'EmployerAggregateRating': '.employer_aggregate_rating',
    'HowToSupply': '.how_to_supply',
    'HowToTool': '.how_to_tool',
    'AMRadioChannel': '.am_radio_channel',
    'FMRadioChannel': '.fm_radio_channel',
    'VideoObjectSnapshot': '.video_object_snapshot',
    'AudioObjectSnapshot': '.audio_object_snapshot',
    'Audiobook': '.audiobook',
    'ImageObjectSnapshot': '.image_object_snapshot',
    'Barcode': '.barcode',
    'CompleteDataFeed': '.complete_data_feed',
    'OpinionNewsArticle': '.opinion_news_article',
    'ReviewNewsArticle': '.review_news_article',
    'ReportageNewsArticle': '.reportage_news_article',
    'BackgroundNewsArticle': '.background_news_article',
    'AnalysisNewsArticle': '.analysis_news_article',
    'AskPublicNewsArticle': '.ask_public_news_article',
    'DiscussionForumPosting': '.discussion_forum_posting',
    'BlogPosting': '.blog_posting',
    'MedicalScholarlyArticle': '.medical_scholarly_article',
    'APIReference': '.api_reference',
    'MediaGallery': '.media_gallery',
    'Newspaper': '.newspaper',
    'ComicSeries': '.comic_series',
    'DisagreeAction': '.disagree_action',
    'DislikeAction': '.dislike_action',
    'WantAction': '.want_action',
    'EndorseAction': '.endorse_action',
    'LikeAction': '.like_action',
    'AgreeAction': '.agree_action',
    'VoteAction': '.vote_action',
    'ScheduleAction': '.schedule_action',
    'CancelAction': '.cancel_action',
    'ReserveAction': '.reserve_action',
    'RejectAction': '.reject_action',
    'AuthorizeAction': '.authorize_action',
    'AcceptAction': '.accept_action',
    'AssignAction': '.assign_action',
    'InsertAction': '.insert_action',
    'WearAction': '.wear_action',
    'CommentAction': '.comment_action',
    'ReplyAction': '.reply_action',
    'CheckOutAction': '.check_out_action',
    'InviteAction': '.invite_action',
    'CheckInAction': '.check_in_action',
    'AskAction': '.ask_action',
    'InformAction': '.inform_action',
    'ShareAction': '.share_action',
    'PsychologicalTreatment': '.psychological_treatment',
    'MedicalTherapy': '.medical_therapy',
    'MedicalSymptom': '.medical_symptom',
    'MedicalSign': '.medical_sign',
    'Vein': '.vein',
    'LymphaticVessel': '.lymphatic_vessel',
    'Artery': '.artery',
    'MaximumDoseSchedule': '.maximum_dose_schedule',
    'ReportedDoseSchedule': '.reported_dose_schedule',
    'RecommendedDoseSchedule': '.recommended_dose_schedule',
    'CovidTestingFacility': '.covid_testing_facility',
    'OnlineMarketplace': '.online_marketplace',
    'PhysiciansOffice': '.physicians_office',
    'IndividualPhysician': '.individual_physician',
    'SkiResort': '.ski_resort',
    'CatholicChurch': '.catholic_church',
    'BrokerageAccount': '.brokerage_account',
    'DepositAccount': '.deposit_account',
    'InvestmentFund': '.investment_fund',
    'MortgageLoan': '.mortgage_loan',
    'CreditCard': '.credit_card',
    'LiveBlogPosting': '.live_blog_posting',
    'VideoGallery': '.video_gallery',
    'ImageGallery': '.image_gallery',
    'AppendAction': '.append_action',
    'PrependAction': '.prepend_action',
    'ConfirmAction': '.confirm_action',
    'RsvpAction': '.rsvp_action',
    'OccupationalTherapy': '.occupational_therapy',
    'PalliativeProcedure': '.palliative_procedure',
    'PhysicalTherapy': '.physical_therapy',
    'RadiationTherapy': '.radiation_therapy',
    'VitalSign': '.vital_sign',
}

def __getattr__(name): 
    mod = importlib.import_module(_lazy_map[name], __name__)
    return getattr(mod, name)

if TYPE_CHECKING:
    for _n, _m in _lazy_map.items():
        globals()[_n] = getattr(importlib.import_module(_m, __name__), _n)
        