from typing import Union, List, Optional
from pydantic import AliasChoices, Field
from schemaorg_models.article import Article


class Report(Article):
    """
A Report generated by governmental or non-governmental organization.
    """
    reportNumber: Optional[Union[str, List[str]]] = Field(default=None,validation_alias=AliasChoices('reportNumber', 'https://schema.org/reportNumber'),serialization_alias='https://schema.org/reportNumber')
