from __future__ import annotations
from pydantic import (
    AliasChoices,
    Field
)
from typing import (
    List,
    Literal,
    Optional,
    Union
)
from .article import Article

class Report(Article):
    """
A Report generated by governmental or non-governmental organization.
    """
    class_: Literal['https://schema.org/Report'] = Field( # type: ignore
        default='https://schema.org/Report',
        alias='@type',
        serialization_alias='@type'
    )
    reportNumber: Optional[Union[str, List[str]]] = Field(
        default=None,
        validation_alias=AliasChoices(
            'reportNumber',
            'https://schema.org/reportNumber'
        ),
        serialization_alias='https://schema.org/reportNumber'
    )
