from typing import List, Literal, Optional, Union
from pydantic import AliasChoices, Field
from schemaorg_models.article import Article


class Report(Article):
    """
A Report generated by governmental or non-governmental organization.
    """
    class_: Literal['https://schema.org/Report'] = Field(default='https://schema.org/Report', alias='class', serialization_alias='class') # type: ignore
    reportNumber: Optional[Union[str, List[str]]] = Field(default=None, validation_alias=AliasChoices('reportNumber', 'https://schema.org/reportNumber'), serialization_alias='https://schema.org/reportNumber')
