from __future__ import annotations
from datetime import (
    date,
    datetime,
    time
)
from pydantic import (
    field_serializer,
    field_validator,
    AliasChoices,
    BaseModel,
    ConfigDict,
    Field,
    HttpUrl
)
from typing import (
    List,
    Literal,
    Optional,
    Union
)
from .intangible import Intangible
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from .offer import Offer
    from .geo_shape import GeoShape
    from .demand import Demand
    from .place import Place
    from .offer_catalog import OfferCatalog
    from .certification import Certification
    from .service_channel import ServiceChannel
    from .physical_activity_category import PhysicalActivityCategory
    from .category_code import CategoryCode
    from .government_benefits_type import GovernmentBenefitsType
    from .opening_hours_specification import OpeningHoursSpecification
    from .thing import Thing
    from .audience import Audience
    from .product import Product
    from .organization import Organization
    from .brand import Brand
    from .aggregate_rating import AggregateRating
    from .image_object import ImageObject
    from .administrative_area import AdministrativeArea
    from .review import Review
    from .person import Person

class Service(Intangible):
    '''
    A service provided by an organization, e.g. delivery service, print services, etc.

    Attributes:
        slogan: A slogan or motto associated with the item.
        logo: An associated logo.
        audience: An intended audience, i.e. a group for whom something was created.
        produces: The tangible thing generated by the service, e.g. a passport, permit, etc.
        hoursAvailable: The hours during which this service or contact is available.
        serviceAudience: The audience eligible for this service.
        termsOfService: Human-readable terms of service documentation.
        award: An award won by or for this item.
        availableChannel: A means of accessing the service (e.g. a phone bank, a web site, a location, etc.).
        isSimilarTo: A pointer to another, functionally similar product (or multiple products).
        offers: An offer to provide this item&#x2014;for example, an offer to sell a product, rent the DVD of a movie, perform a service, or give away tickets to an event. Use [[businessFunction]] to indicate the kind of transaction offered, i.e. sell, lease, etc. This property can also be used to describe a [[Demand]]. While this property is listed as expected on a number of common types, it can be used in others. In that case, using a second type, such as Product or a subtype of Product, can clarify the nature of the offer.
      
        providerMobility: Indicates the mobility of a provided service (e.g. 'static', 'dynamic').
        brand: The brand(s) associated with a product or service, or the brand(s) maintained by an organization or business person.
        review: A review of the item.
        broker: An entity that arranges for an exchange between a buyer and a seller.  In most cases a broker never acquires or releases ownership of a product or service involved in an exchange.  If it is not clear whether an entity is a broker, seller, or buyer, the latter two terms are preferred.
        provider: The service provider, service operator, or service performer; the goods producer. Another party (a seller) may offer those services or goods on behalf of the provider. A provider may also serve as the seller.
        category: A category for the item. Greater signs or slashes can be used to informally indicate a category hierarchy.
        serviceArea: The geographic area where the service is provided.
        hasOfferCatalog: Indicates an OfferCatalog listing for this Organization, Person, or Service.
        hasCertification: Certification information about a product, organization, service, place, or person.
        serviceType: The type of service being offered, e.g. veterans' benefits, emergency relief, etc.
        aggregateRating: The overall rating, based on a collection of reviews or ratings, of the item.
        areaServed: The geographic area where a service or offered item is provided.
        isRelatedTo: A pointer to another, somehow related product (or multiple products).
        serviceOutput: The tangible thing generated by the service, e.g. a passport, permit, etc.
    '''
    class_: Literal['https://schema.org/Service'] = Field( # type: ignore
        default='https://schema.org/Service',
        alias='@type',
        serialization_alias='@type'
    )
    slogan: Optional[Union[str, List[str]]] = Field(
        default=None,
        validation_alias=AliasChoices(
            'slogan',
            'https://schema.org/slogan'
        ),
        serialization_alias='https://schema.org/slogan'
    )
    logo: Optional[Union[HttpUrl, List[HttpUrl], 'ImageObject', List['ImageObject']]] = Field(
        default=None,
        validation_alias=AliasChoices(
            'logo',
            'https://schema.org/logo'
        ),
        serialization_alias='https://schema.org/logo'
    )
    audience: Optional[Union['Audience', List['Audience']]] = Field(
        default=None,
        validation_alias=AliasChoices(
            'audience',
            'https://schema.org/audience'
        ),
        serialization_alias='https://schema.org/audience'
    )
    produces: Optional[Union['Thing', List['Thing']]] = Field(
        default=None,
        validation_alias=AliasChoices(
            'produces',
            'https://schema.org/produces'
        ),
        serialization_alias='https://schema.org/produces'
    )
    hoursAvailable: Optional[Union['OpeningHoursSpecification', List['OpeningHoursSpecification']]] = Field(
        default=None,
        validation_alias=AliasChoices(
            'hoursAvailable',
            'https://schema.org/hoursAvailable'
        ),
        serialization_alias='https://schema.org/hoursAvailable'
    )
    serviceAudience: Optional[Union['Audience', List['Audience']]] = Field(
        default=None,
        validation_alias=AliasChoices(
            'serviceAudience',
            'https://schema.org/serviceAudience'
        ),
        serialization_alias='https://schema.org/serviceAudience'
    )
    termsOfService: Optional[Union[HttpUrl, List[HttpUrl], str, List[str]]] = Field(
        default=None,
        validation_alias=AliasChoices(
            'termsOfService',
            'https://schema.org/termsOfService'
        ),
        serialization_alias='https://schema.org/termsOfService'
    )
    award: Optional[Union[str, List[str]]] = Field(
        default=None,
        validation_alias=AliasChoices(
            'award',
            'https://schema.org/award'
        ),
        serialization_alias='https://schema.org/award'
    )
    availableChannel: Optional[Union['ServiceChannel', List['ServiceChannel']]] = Field(
        default=None,
        validation_alias=AliasChoices(
            'availableChannel',
            'https://schema.org/availableChannel'
        ),
        serialization_alias='https://schema.org/availableChannel'
    )
    isSimilarTo: Optional[Union['Service', List['Service'], 'Product', List['Product']]] = Field(
        default=None,
        validation_alias=AliasChoices(
            'isSimilarTo',
            'https://schema.org/isSimilarTo'
        ),
        serialization_alias='https://schema.org/isSimilarTo'
    )
    offers: Optional[Union['Demand', List['Demand'], 'Offer', List['Offer']]] = Field(
        default=None,
        validation_alias=AliasChoices(
            'offers',
            'https://schema.org/offers'
        ),
        serialization_alias='https://schema.org/offers'
    )
    providerMobility: Optional[Union[str, List[str]]] = Field(
        default=None,
        validation_alias=AliasChoices(
            'providerMobility',
            'https://schema.org/providerMobility'
        ),
        serialization_alias='https://schema.org/providerMobility'
    )
    brand: Optional[Union['Organization', List['Organization'], 'Brand', List['Brand']]] = Field(
        default=None,
        validation_alias=AliasChoices(
            'brand',
            'https://schema.org/brand'
        ),
        serialization_alias='https://schema.org/brand'
    )
    review: Optional[Union['Review', List['Review']]] = Field(
        default=None,
        validation_alias=AliasChoices(
            'review',
            'https://schema.org/review'
        ),
        serialization_alias='https://schema.org/review'
    )
    broker: Optional[Union['Person', List['Person'], 'Organization', List['Organization']]] = Field(
        default=None,
        validation_alias=AliasChoices(
            'broker',
            'https://schema.org/broker'
        ),
        serialization_alias='https://schema.org/broker'
    )
    provider: Optional[Union['Person', List['Person'], 'Organization', List['Organization']]] = Field(
        default=None,
        validation_alias=AliasChoices(
            'provider',
            'https://schema.org/provider'
        ),
        serialization_alias='https://schema.org/provider'
    )
    category: Optional[Union['PhysicalActivityCategory', List['PhysicalActivityCategory'], 'CategoryCode', List['CategoryCode'], str, List[str], 'Thing', List['Thing'], HttpUrl, List[HttpUrl]]] = Field(
        default=None,
        validation_alias=AliasChoices(
            'category',
            'https://schema.org/category'
        ),
        serialization_alias='https://schema.org/category'
    )
    serviceArea: Optional[Union['AdministrativeArea', List['AdministrativeArea'], 'GeoShape', List['GeoShape'], 'Place', List['Place']]] = Field(
        default=None,
        validation_alias=AliasChoices(
            'serviceArea',
            'https://schema.org/serviceArea'
        ),
        serialization_alias='https://schema.org/serviceArea'
    )
    hasOfferCatalog: Optional[Union['OfferCatalog', List['OfferCatalog']]] = Field(
        default=None,
        validation_alias=AliasChoices(
            'hasOfferCatalog',
            'https://schema.org/hasOfferCatalog'
        ),
        serialization_alias='https://schema.org/hasOfferCatalog'
    )
    hasCertification: Optional[Union['Certification', List['Certification']]] = Field(
        default=None,
        validation_alias=AliasChoices(
            'hasCertification',
            'https://schema.org/hasCertification'
        ),
        serialization_alias='https://schema.org/hasCertification'
    )
    serviceType: Optional[Union['GovernmentBenefitsType', List['GovernmentBenefitsType'], str, List[str]]] = Field(
        default=None,
        validation_alias=AliasChoices(
            'serviceType',
            'https://schema.org/serviceType'
        ),
        serialization_alias='https://schema.org/serviceType'
    )
    aggregateRating: Optional[Union['AggregateRating', List['AggregateRating']]] = Field(
        default=None,
        validation_alias=AliasChoices(
            'aggregateRating',
            'https://schema.org/aggregateRating'
        ),
        serialization_alias='https://schema.org/aggregateRating'
    )
    areaServed: Optional[Union['GeoShape', List['GeoShape'], str, List[str], 'AdministrativeArea', List['AdministrativeArea'], 'Place', List['Place']]] = Field(
        default=None,
        validation_alias=AliasChoices(
            'areaServed',
            'https://schema.org/areaServed'
        ),
        serialization_alias='https://schema.org/areaServed'
    )
    isRelatedTo: Optional[Union['Service', List['Service'], 'Product', List['Product']]] = Field(
        default=None,
        validation_alias=AliasChoices(
            'isRelatedTo',
            'https://schema.org/isRelatedTo'
        ),
        serialization_alias='https://schema.org/isRelatedTo'
    )
    serviceOutput: Optional[Union['Thing', List['Thing']]] = Field(
        default=None,
        validation_alias=AliasChoices(
            'serviceOutput',
            'https://schema.org/serviceOutput'
        ),
        serialization_alias='https://schema.org/serviceOutput'
    )
